pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  - mv public/.public/302.html public/.public/resume.html
  artifacts:
    paths:
    - public
  only:
  - master
